name: Docs Deployment GCP

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    if: |
      (github.event_name == 'pull_request' && startsWith(github.head_ref, 'hosted/')) || 
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') || 
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/build_and_deploy_gcp.yml
    with:
      environment: ${{(github.ref == 'refs/heads/dev' && 'dev') || 
                    (github.ref == 'refs/heads/main' && 'staging') || 
                    (github.event_name == 'pull_request' && 'dev')}}
      core_app: ${{ github.ref == 'refs/heads/main' && 'polygon-docs-main' || 'polygon-docs-dev' }}
    secrets: inherit
