name: Hosted PR and Dev Deployment
on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    branches:
      - dev
      - hosted/**
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    secrets: inherit
