name: Hosted PR and Dev Deployment
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    secrets: inherit