name: hosted branch pr deployment
on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    if: startsWith(github.head_ref, 'hosted/') || github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/build_and_deploy.yml
    secrets: inherit